#!/bin/bash

command_exists() {
    # check if command exists and fail otherwise
    command -v "$1" >/dev/null 2>&1
    if [[ $? -ne 0 ]]; then

	echo "########################################################"
        echo "$1 not installed................!!!!!!!!!!!!!!!!!!!!!!!"
	echo "########################################################"

	sudo apt install $1
        #exit 1
    fi
}

for COMMAND in "awk" "sed" "grep" "tar" "gzip" "which" "openssl" "curl" "alacritty" "tlp" "ncdu" "git"; do
    command_exists "${COMMAND}"
done
