#!/usr/bin/env bash
# This script is meant to alert when the ba3 is 96% and still charging
# To keep the ba3 life...
#


ba3_level=$(cat /sys/class/power_supply/BAT1/capacity)

ba3_status=$(cat /sys/class/power_supply/BAT1/status)


if [ $ba3_level -ge  96 ] && [ $ba3_status == "Charging" ]; then
	
	notify-send "remove charger"
	espeak "remove charger"

fi


