#!/usr/bin/env bash
#ba3 full alert script
# To save the ba3 life...
#


ba3_level=$(cat /sys/class/power_supply/BAT1/capacity)

ba3_status=$(cat /sys/class/power_supply/BAT1/status)


while [ $ba3_level -ge  93 ]  && [ "$ba3_status" = "Charging" ];
do
		echo "checked"
		echo 3024 | sudo tee /sys/class/backlight/intel_backlight/brightness > /dev/null
		sleep 2
		echo 400 | sudo tee /sys/class/backlight/intel_backlight/brightness > /dev/null
		sleep 2

		if [[ $ba3_level -ge 94 ]]; then
				break

		elif [ "$ba3_status" = "Discharging" ]; then
				break
		fi
done

echo 500 | sudo tee /sys/class/backlight/intel_backlight/brightness > /dev/null
