#!/usr/bin/env bash
#
#
#
#



exp_ba3=25
ba3_level="$(cat /sys/class/power_supply/BAT1/capacity)"

ba3_status="$(cat /sys/class/power_supply/BAT1/status)"

if [ $ba3_level -eq $exp_ba3 ] && [ $ba3_status == "Discharging" ]; then 

	espeak "plug charger"

fi


