#!/bin/bash


echo stoping apache2....
sudo service apache2 stop
echo stopped

echo stoping mysql....
sudo service mysql stop
echo stopped

echo stoping bluetooth....
sudo service bluetooth stop
echo stopped

echo stoping mongodb....
sudo service mongodb stop
echo stopped

echo stoping redis-server....
sudo service redis-server stop
echo stopped

echo stoping nginx....
sudo service nginx stop
echo stopped

echo stoping postgresql....
sudo service postgresql stop
echo stopped

notify-send "Done with stop processes *88888888888888888888888888888888888888888888*****************88888888888888
 thi s a g qeat  a g qew 
" -i /home/evad/Pictures/Wallpapers/wp1828918-programmer-wallpapers.jpg
