#!/bin/bash

load="loading......."
clean="cleaning....."



echo "loading........."
echo "freeing up space...."


echo "removing unneeded packages"
sudo apt autoremove
echo "done"


echo "cleaning up apt cache::"

echo "apt cache"
sudo du -sh /var/cache/apt 
echo "$clean"
sudo apt autoclean

echo "systemd journal logs"
journalctl --disk-usage
sudo journalctl --vacuum-time=3d

#snap applications 
echo "snap application"
./snap

#thumbnails/* 
rm -rf ~/.cache/thumbnails/*


