#!/bin/bash

#had an mouse tap issue on lxqt which i use to minmise my ram usage 

#this is the best fix i could find for now


# "xinput 
# xinput list
# this list the stdio connected devices
# interested in the "Synaptics TouchPad"

# xinput list-props 11 on my computer

# this makes tapping enabled 

# "libinput Tapping Enabled (310): 0"

xinput set-prop 11 310 1

