#!/bin/bash

# This needs a rewrite

start(){
	echo ddd
}


stop(){

#echo stoping apache2....
#sudo service apache2 stop
#echo stopped

echo stoping mysql....
sudo service mysql stop
echo stopped

echo stoping mongodb....
sudo service mongodb stop
echo stopped

echo stoping redis-server....
sudo service redis-server stop
echo stopped

# Bluetooth
sudo service bluetooth stop
echo bluetooth stopped

echo stoping nginx....
sudo service nginx stop
echo stopped

echo stoping postgresql....
sudo service postgresql stop
echo stopped

notify-send "Done!!"

}


case $1 in 
	start|stop) "$1" ;;
esac
