#!/bin/bash

# This needs a rewrite

start(){
	echo ddd
}


stop(){

#echo stoping apache2....
#sudo service apache2 stop
#echo stopped

echo stoping mysql....
sudo systemctl stop mysql 
echo stopped



echo stoping mongodb....
sudo systemctl stop mongodb 
echo stopped


echo stoping redis-server....
sudo systemctl stop redis-server 
echo stopped


# Bluetooth
echo stoping bluetooth devices
sudo systemctl stop bluetooth
echo bluetooth stopped


echo stoping nginx....
sudo systemctl stop nginx
echo nginx stopped

echo stoping postgresql....
sudo systemctl stop postgresql
echo postgresql stopped

notify-send "Done!!"

# Docker
sudo systemctl stop docker.service
sudo systemctl stop docker.socket
}



case $1 in
	start|stop) "$1" ;;
esac
