#!/bin/bash

# Symbolic link for bash_setup

# .bashrc
ln -sf ~/.sys_s/src/sys_config/bash_conf/.bashrc ~/.bashrc

# .bash_profile
ln -sf ~/.sys_s/src/sys_config/bash_conf/.bash_profile ~/.bash_profile

# .profile
ln -sf ~/.sys_s/src/sys_config/bash_conf/.profile ~/.profile

echo "### synced .bashrc .bash_profile .profile"