#!/bin/bash
#install scripts //dev tools

sudo apt update
sudo apt upgrade

#git 
sudo add-apt-repository ppa:git-core/ppa
sudo apt update
sudo apt install git


sudo apt install make
sudo apt install build-essential
sudo apt install htop

#_pyenv
#version manager for python
git clone https://github.com/pyenv/pyenv.git ~/.pyenv
echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc


#tlp use tlpui if needed
sudo apt install tlp

#nvm js version manager 
echo check nvm for js version manager if needed

#Sdkman java version manager and others related
curl -s "https://get.sdkman.io" | bash
source "$HOME/.sdkman/bin/sdkman-init.sh"

#vim 
sudo apt install vim

#alternative to stick note @windows //indicator stickynote
sudo add-apt-repository ppa:umang/indicator-stickynotes
sudo apt update
sudo apt install indicator-stickynotes

#tmux screen multiplexer
sudo apt install tlp

#offline docs
sudo apt install zeal

#gpu based terminal emulator
sudo apt install alacritty


