#!/usr/bin/env bash

#set up for dev_env

#alacritty
if [ ! -d "$HOME/.config/alacritty" ] && [ ! -L "$HOME/.config/alacritty/alacritty.yml" ]; then 

	echo "#################################################################"
	echo " creating a directory for Alacritty && ln config file for"
	mkdir ~/.config/alacritty       
	ln -sf ~/.sys_s/src/dev_env/alacritty.yml $HOME/.config/alacritty/alacritty.yml
	echo "Done..........!!!!"
	echo "#################################################################"
	
		
elif  [ -d "$HOME/.config/alacritty" ] && [ ! -L "$HOME/.config/alacritty/alacritty.yml" ]; then 

        echo "creating ln, dir exist"
        ln -sf ~/.sys_s/src/dev_env/alacritty.yml $HOME/.config/alacritty/alacritty.yml
    
     
fi

# TODO
# check if a binary file exist 
# better output

