#!/bin/bash
# The environment variable for android and related setups

#ANDROID
export ANDROID_HOME=/home/$USER/Android/Sdk
export ANDROID_SDK=/home/$USER/Android/Sdk
export PATH=/home/$USER/Android/Sdk:$PATH
export PATH=/home/$USER/Android/Sdk/platform-tools:$PATH
export PATH=/home/$USER/Android/Sdk/tools/bin:$PATH
export PATH=/home/$USER/Android/Sdk/platforms:$PATH
export PATH=/home/$USER/Android/Sdk/emulator:$PATH

#Android bin
export PATH=$PATH:/opt/android-studio/bin

#notify-send "works"
